<a href="https://colab.research.google.com/github/andresvc21/Cracking_Code_Interview_PY/blob/main/Numpy_Gnerals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
5*np.ones(10)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [10]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [11]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [13]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.random.rand()

0.6507260485336512

In [17]:
np.random.randn(25)

array([-0.57005548, -0.96195111,  0.80858402,  0.13731619, -1.17683923,
       -0.43741028, -0.81615652, -1.11506947,  1.63692213, -0.56773292,
        1.64528798,  0.96596865, -1.54251853, -0.40380452, -1.15382717,
        0.53625403,  1.10392541, -0.80518796,  1.20697327, -1.15696356,
       -0.03225263, -0.33385004, -0.41670441,  0.73159119, -1.77629184])

In [19]:
np.array(10)

array(10)

In [21]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [24]:
nat=np.arange(1,26).reshape(5,5)
print(nat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [25]:
nat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [26]:
nat[3,4]

20

In [28]:
nat[0:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [29]:
nat.sum()

325

In [30]:
nat.std()

7.211102550927978

In [31]:
nat.sum(axis=1)

array([ 15,  40,  65,  90, 115])

In [32]:
z=np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [33]:
print(z.shape)

(10,)


In [35]:
z.shape=(10,1)
print(z)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [36]:
np.empty(3)

array([1., 1., 1.])

In [38]:
list=[10,20]
list

[10, 20]

In [39]:
np.array(list)

array([10, 20])

In [41]:
np.random.seed(0)
z1=np.random.randint(10, size=6)
z1

array([5, 0, 3, 3, 7, 9])

In [42]:
z=np.array([1,2,3,4,5])

In [43]:
z[z>3]

array([4, 5])

In [45]:
np.where(z>3, z, 2) #very usefull with photos

array([2, 2, 2, 4, 5])